### ISSUE TITLE
Mandrill Renders all HTML Emails with HTML Tags

### ISSUE THREAD

**Issue by osseonews** [swissup/module-email#14]
When using this extension with Mandrill all HTML emails are sent with the HTML tags inline and the emails are impossible to read. Initially, we though this was due to settings in Mandrill for HTML emails, but we played around with all the Mandrill settings and nothing worked. The extension is unusable with Mandrill because the emails are delivered as text emails with HTML tags included, which makes them impossible read. Notably, when switching back to the regular Magento core email setup, the emails display fine. A simple code like this will display exactly like this when send email via Mandrill with this plugin:
`<p><strong>Your Order</strong></p>`

This is actually what the customer sees. The HTML tags.

**Comment by roma84** [comment]
Please contact our support to fix the issue: https://swissuplabs.com/contacts/
We can't fix it because it requires Mandrill API access.
