### ISSUE TITLE
Extension fails automatic tests on Marketplace

### ISSUE THREAD

**Issue by dimdimich** [swissup/module-email#15]
PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/bin/composer/src/Composer/DependencyResolver/Solver.php on line 223

Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/bin/composer/src/Composer/DependencyResolver/Solver.php on line 223

Any idea?

![Screenshot_2020-11-11 Magento Marketplace - Developer Portal](https://user-images.githubusercontent.com/5389109/98833736-ab925b80-243e-11eb-855f-27f008156733.png)

**Comment by 0m3r** [comment]
look very strange

**Comment by 0m3r** [comment]
do you have any other logs?

**Comment by dimdimich** [comment]
No, logs. I contacted Marketplace support and got next answer: 

Hello there!

Thank you for reaching out! You can test using the EQP tools before submitting for review. Due to staffing we no longer assist with varnish failures and we do not provide manual reviews. Please utilize the below tools and reach out to community engineering you have trouble.

https://github.com/magento/magento-coding-standard

And for more info please go here:

https://devdocs.magento.com/marketplace/sellers/code-validation.html

If you have further questions please join the community engineering slack.

https://devdocs.magento.com/community/resources/resources.html

Jenn K.
Magento Marketplace Support

**Comment by 0m3r** [comment]
We already run MEQP validation at our ci server after each commit

**Comment by 0m3r** [comment]
Required packages do not install properly
```
php -d memory_limit=2G /usr/local/bin/composer require aws/aws-sdk-php-zf2  slm/mail
```

![Screenshot from 2020-11-13 15-40-13](https://user-images.githubusercontent.com/412612/99078331-e6270000-25c6-11eb-9b73-f9220d84ed87.png)
![Screenshot from 2020-11-13 15-39-29](https://user-images.githubusercontent.com/412612/99078334-e7582d00-25c6-11eb-9519-397a61e28f26.png)

**Comment by dimdimich** [comment]
Can we make this packages optional so we can reduce ammount of memmory needed?

**Comment by vovayatsyuk** [comment]
Do we need this module at the marketplace? 

Asking because when you'll add it to the marketplace it will be updatable from the marketplace only. This means that the new versions will not be visible to the customers till you update it on the marketplace.

For now, it's visible from packagist.org and instantly updates for all clients.

Long story short: It's better to keep free modules **on packagist.org only** to make it easier to run "composer update" and instantly receive the latest version.

**Comment by dimdimich** [comment]
We really need it. It will help us to cross promote our other modules and much more customers are browsing on Marketplace then on other sites.

**Comment by 0m3r** [comment]
peak: 2184.92MiB

```
php -d memory_limit=3G /usr/local/bin/composer require swissup/email  --profile
...
[739.6MiB/21.47s] Memory usage: 739.56MiB (peak: 2184.92MiB), time: 21.47s
```

**Comment by dimdimich** [comment]
Can we make this package optional in order to reduce ammout of required memmory?

**Comment by 0m3r** [comment]
Optional?  composer doesn't support optional dependencies.
>[Adding optional dependencies are not worth the trouble IMO in composer..](https://github.com/composer/composer/issues/8184)

Of course, we can remove Mandrill and Amazon SES support
if you want but I think it will be a bad decision.

**Comment by roma84** [comment]
https://getcomposer.org/doc/04-schema.md#suggest

**Comment by 0m3r** [comment]
> https://getcomposer.org/doc/04-schema.md#suggest

There is no version constraint for suggests as you are suggesting
It's "package/name": "description/reason for suggesting".

**Comment by 0m3r** [comment]
try to install the last swissup/email version

```
composer require swissup/email:0.3.14
```

[737.1MiB/22.03s] Memory usage: 737.13MiB (**peak: 1966.16MiB**), time: 22.03s
![Screenshot from 2020-11-16 19-09-29](https://user-images.githubusercontent.com/412612/99284726-49bb6280-283f-11eb-8109-74b0b518ca35.png)

**Comment by dimdimich** [comment]
I was able to submit extension now. Thanks!
