### ISSUE TITLE
Extension rejected from marketplace

### ISSUE THREAD

**Issue by dimdimich** [swissup/module-email#16]
Test environments Used:

Magento ver. 2.4.1 Community Edition (PHP 7.4.10)
Magento ver. 2.4.1 Enterprise Edition (PHP 7.4.10)

Steps:
1. Go to Admin and enable the module.
2. Go to Marketing > Communications > Email Services and click on the "Add New" button.
3. Click on the "Check Service" button.

Expected result: The button must work correctly.

Actual result: Appears an error

Was found on Magento version(s):

Magento ver. 2.4.1 Community Edition (PHP 7.4.10)
Magento ver. 2.4.1 Enterprise Edition (PHP 7.4.10)

The version of the browser:
Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)

Video: https://bluejeans.com/s/w@y6wRKlcJ3
Logs: Yes

**Comment by 0m3r** [comment]
https://github.com/swissup/module-email/commit/c58606f2079e538efb57f8390febf9dffb96fbb5

**Comment by 0m3r** [comment]
Please ask what he means when says "correctly"?

**Comment by dimdimich** [comment]
I can't ask them directly.

**Comment by 0m3r** [comment]
https://github.com/swissup/email/releases/0.3.15
