### ISSUE TITLE
Email Logs column 'from' sorting mysql error

### ISSUE THREAD

**Issue by dimdimich** [swissup/module-email#17]
Test Environments Used:
Magento ver. 2.4.1 Enterprise Edition (PHP 7.4.10)
Magento ver. 2.3.6 Community Edition (PHP 7.3.22)

Reasons for failure:
Infinite loading and an error appear \ "Something went wrong." \ on the page \ "Marketing → Communications → Email Logs" \ after sorting by column \"From"\

Steps:
1. Install Magento with this extension
2. Go to Magento Admin Panel → Marketing → Communications → Email Logs
3. Click to sort by column \" From"\

Expected result:
Sorting by the column \" From"\working correctly

Actual result:
Infinity load after using sorting by the column \" From"\. An error appears \" Something went wrong"\. The browser console error. Please, see attached file.

Was found on Magento version(s) + PHP version(s):
Magento ver. 2.4.1 Enterprise Edition (PHP 7.4.10)
Magento ver. 2.3.6 Community Edition (PHP 7.3.22)

**Comment by 0m3r** [comment]
Not reproduce at 2.3.5 
![Screenshot from 2020-11-19 18-13-30](https://user-images.githubusercontent.com/412612/99692438-fe998d80-2a92-11eb-980b-c1ffb0bcb90d.png)

**Comment by roma84** [comment]
https://prnt.sc/vmafu1

**Comment by 0m3r** [comment]
FROM is a reserved word.

wrong:
```sql
 SELECT `main_table`.* FROM `swissup_email_history` AS `main_table` ORDER BY from ASC LIMIT 2;
```
right:
```sql
 SELECT `main_table`.* FROM `swissup_email_history` AS `main_table` ORDER BY `from` ASC LIMIT 2;
```

**Comment by 0m3r** [comment]
To is also a reserved word.

**Comment by 0m3r** [comment]
https://github.com/swissup/email/releases/0.3.16
