### ISSUE TITLE
Check service' option isn`t working.

### ISSUE THREAD

**Issue by dimdimich** [swissup/module-email#18]
Test environments Used:

Magento ver. 2.4.1 Community Edition (PHP 7.4.10)
Magento ver. 2.4.1 Enterprise Edition (PHP 7.4.10)

Reason for failure:

1. 'Check service' option isn`t working. "There has been an error processing your request" the error message is displayed

Steps:

1. Go to Marketing -> Communications -> Email Services
2. Press the “Add new” button
3. Create service
4. Click the 'Save and Continue' button
5. Click the 'Check service' button

ER: The service is checked successfully.

AR: The error message is displayed. "There has been an error processing your request"

Was found on Magento version(s):

Magento ver. 2.4.1 Community Edition (PHP 7.4.10)
Magento ver. 2.4.1 Enterprise Edition (PHP 7.4.10)

 

Version of browser:
Version 85.0.4183.102 (Official Build) (64-bit)

Video: https://bluejeans.com/s/eoV8IlFRlVm/

**Comment by 0m3r** [comment]
Check Service means checking SMTP, Sendmail, or mandrill connection (credentials), etc.

Is she use the right SMTP credentials?
Give me their exception log
I can't fix this error without an error trace

**Comment by dimdimich** [comment]
Pleas check attached 
[fb87229a490e39cb356f374097dd4ecf.zip](https://github.com/swissup/module-email/files/5574969/fb87229a490e39cb356f374097dd4ecf.zip)

**Comment by 0m3r** [comment]
```log
Deprecated Functionality: Invalid characters passed for attempted conversion, these have been ignored in /var/www/html/vendor/swissup/module-email/Controller/Adminhtml/Email/Service/Check.php on line 96
```

**Comment by 0m3r** [comment]
![Screenshot from 2020-11-20 19-11-58](https://user-images.githubusercontent.com/412612/99828936-4b00ce00-2b64-11eb-9549-a02712aa68c3.png)

**Comment by 0m3r** [comment]
https://github.com/swissup/email/releases/0.3.17
