### ISSUE TITLE
Gmail "check service" Extension rejected from marketplace

### ISSUE THREAD

**Issue by dimdimich** [swissup/module-email#19]
Review Results:

Test environments used:

Magento ver. 2.4.1 Commerce on Cloud (PHP 7.4.9)
Magento ver. 2.3.6 Commerce on Cloud (PHP 7.3.21)

Reasons for failure:

Something went wrong while checking the service

Summary:

Steps:
1. Go to Marketing > Communications > Email Services
2. Click "Add New" button and save.
- Name: Gmail
- Type: Gmail
3. Select "Default Transport Email Service": Gmail
4. Click on the "Check Service" button.

Expected result: page opens without any errors

Actual result: Something went wrong while checking the service. Original error message : 5.7.14 5.7.14 Please log in via your web browser and then try again. 5.7.14 Learn more at 5.7.14 https://support.google.com/mail/answer/78754 q188sm2901152pfc.204 - gsmtp
Please, see attached file

Was found on Magento version: Magento ver. 2.4.1 Commerce on Cloud,
Full PHP Version: PHP 7.4.9

Was found on Magento version: Magento ver. 2.3.6 Commerce on Cloud
Full PHP Version: 7.3.21

Version of browser (browsers): Chrome Version 77.0.3865.90 (Official Build) (64-bit)

Video: https://bluejeans.com/s/FCokh3myzsH/
[09d6fc8cd0a59ce8062fa12759a529cf.zip](https://github.com/swissup/module-email/files/5582927/09d6fc8cd0a59ce8062fa12759a529cf.zip)

**Comment by 0m3r** [comment]
Look like the answer is in your question - https://support.google.com/mail/answer/78754 

![Screenshot from 2020-11-23 14-50-31](https://user-images.githubusercontent.com/412612/99964056-63a6f900-2d9b-11eb-8d58-47ba38531ea3.png)


Do you use a Gmail App password?
Are you checking your Gmail SMTP credentials before?

>If field Type selects Gmail. Use an App Password: Generate a new App Password for your account. https://security.google.com/settings/security/apppasswords

![Screenshot from 2020-11-23 14-46-46](https://user-images.githubusercontent.com/412612/99963725-e11e3980-2d9a-11eb-9a61-db6fbec2cc07.png)

**Comment by dimdimich** [comment]
They are insisting that we should add it to our user guide. Can you add to doc.swissuplabs.com and i will resubmit guide?

> 
> Thank you for this info and we can pass it along, but we ask that you add this information to your user install guide for both users and QA as it is clear this was not obvious to the QA team, and therefore likely will not be obvious to a user either.
> 
> Please update the user guide and resubmit.g

**Comment by 0m3r** [comment]
It is already added to our user guide.
https://docs.swissuplabs.com/m2/extensions/email/usage/


![Screenshot from 2020-11-23 14-46-46](https://user-images.githubusercontent.com/412612/99963725-e11e3980-2d9a-11eb-9a61-db6fbec2cc07.png)

**Comment by 0m3r** [comment]
https://docs.swissuplabs.com/m2/extensions/email/usage/#gmail-service-setup
