### ISSUE TITLE
Extension breaks email sending when name contains non-ASCII char

### ISSUE THREAD

**Issue by mokadev** [swissup/module-email#20]
When this extension is enabled all email are sent with the non ASCII chars (ex: â, é, ...) stripped from the subject and sender name

The same problem was happening before on Magento with Dotmailer activated https://github.com/magento/magento2/issues/24902

**Comment by 0m3r** [comment]
Yes, we filter non-ASCII characters in headers. Look like email RFC(s) don't allow non-ASCII characters in headers, but some email providers work properly with it.

https://github.com/laminas/laminas-mail/issues/67
https://github.com/laminas/laminas-validator/issues/7
https://github.com/laminas/laminas-mail/issues/57

So I add filtering in this commit  https://github.com/swissup/module-email/commit/432dbb0e42253f963f3af19c4a993e84f7f6fd25
And I also dislike this workaround.  
You can disable this behavior [here (Mail/Message/Convertor.php) ](https://github.com/swissup/module-email/blob/master/Mail/Message/Convertor.php#L56-L66)
and test in your environment

p.s. if you have a nice patch please send me it

**Comment by mokadev** [comment]
Hi 

thanks for the answers i will test it . It's weird that if the sender's name is "Frédérique" his name become "Frdrique" ....

**Comment by 0m3r** [comment]
are you tried to disable filtering for itself?

https://github.com/swissup/module-email/blob/master/Mail/Message/Convertor.php#L56-L58

```php 
                    $headerValue = \Zend\Mail\Header\HeaderValue::filter(
                        $headerValue
                    );
```

**Comment by wilfriedwolf** [comment]
Just created a PR to solve the problem...
Best regards and thanks for the cool (and ad-free :) module

**Comment by 0m3r** [comment]
@wilfriedwolf  :1st_place_medal: 

I found my old proposal to Magento

https://github.com/magento/magento2/issues/19876
https://github.com/magento/magento2/pull/20441
