### ISSUE TITLE
Poor performance when having a larga email history

### ISSUE THREAD

**Issue by paugnu** [swissup/module-email#24]
Hi,

I've been using this module for a year now, it is great.

However, I've found that there is a poor performance when the number of emails in history is large (near 100000).

I've solved this, adding an index to the table in the following way:
`ALTER TABLE swissup_email_history ADD INDEX created_entity_ndx (created_at,entity_id);`

**Comment by 0m3r** [comment]
Thank you for the recommendation.
It's really my fault I never tested with a large number of records

https://github.com/swissup/module-email/blob/master/view/adminhtml/ui_component/email_history_listing.xml#L73
