### ISSUE TITLE
Magento 2.4.6 support

### ISSUE THREAD

**Issue by jorgb90** [swissup/module-email#28]
Because Zendframework1 is removed this gives an error on compilation:

https://github.com/swissup/module-email/blob/master/Mail/Message/Convertor/Zend1FakeTransport.php

**Comment by 0m3r** [comment]
https://github.com/swissup/module-email/commit/597efecee2a5289b1240d5f2e7c7f37ed240d813

**Comment by 0m3r** [comment]
Try new release
https://github.com/swissup/email/releases/0.5.7
