### ISSUE TITLE
Password is truncated

### ISSUE THREAD

**Issue by roma84** [swissup/module-email#29]
### Preconditions
This issue has been confirmed on multiple Magento 2.4.4+ with the plugin version 0.5.8

### Describe the problem
When we try to register a Sendgrid Api Key the password is truncated in the database

### Steps to reproduce:

1. create a sendgrid API key (or use a 69 chars password)
2. register a service using this 69+ chars password
3. the service is saved but password does not appears anymore

### Expected result
the full encrypted password should be stored in database

### Actual result
only the first chars are registered (truncate by the column size limit)

Has the world evolves to longer API keys the password column should be at least 255 chars or converted to text field

**Comment by 0m3r** [comment]
![image](https://github.com/swissup/module-email/assets/412612/92fbf929-8fe7-407d-bdad-8af5f4afe2ac)
![image](https://github.com/swissup/module-email/assets/412612/4087ec83-2cf8-4e1c-ab4f-acab4dcce7b4)

**Comment by 0m3r** [comment]
![image](https://github.com/swissup/module-email/assets/412612/b638ae66-6611-46ef-a27d-b9215b99477e)
