### ISSUE TITLE
Feature request: OAuth for Gmail / Google Workspace

### ISSUE THREAD

**Issue by Jeroen999** [swissup/module-email#31]
Google requires OAuth for Gmail / Google Workspace from 15-6-2024.

**Comment by 0m3r** [comment]
Info 
- https://workspaceupdates.googleblog.com/2023/09/winding-down-google-sync-and-less-secure-apps-support.html
- https://support.google.com/a/answer/14114704?hl=en
- https://mezha.media/en/2024/01/19/google-workspace-and-gmail-will-no-longer-support-login-via-login-and-password-in-programs-only-oauth-will-remain/

- https://mailtrap.io/blog/phpmailer-gmail/
- https://github.com/PHPMailer/PHPMailer/wiki/Using-Gmail-with-XOAUTH2
- https://github.com/PHPMailer/PHPMailer/pull/421/files
- https://github.com/thephpleague/oauth2-google
- https://postmansmtp.com/how-to-configure-post-smtp-with-gmailgsuite-using-oauth/?utm_source=wp_org&utm_medium=read_me

**Comment by 0m3r** [comment]
as soon as I have enough "free" time for it

**Comment by 0m3r** [comment]
It works 
![image](https://github.com/swissup/module-email/assets/412612/334a9ed9-b66c-48f0-bb5b-62e765161044)

**Comment by Jeroen999** [comment]
Thank you! I can also confirm that it is working.

**Comment by 0m3r** [comment]
Similar configuration - [Setting Up POP3 Importing with OAuth via Google](https://help.whmcs.com/m/support_tools/l/1328652-setting-up-pop3-importing-with-oauth-via-google)

**Comment by 0m3r** [comment]
![image](https://github.com/swissup/module-email/assets/412612/e250f681-8381-4846-9bcf-790bafa72cde)
https://stackoverflow.com/questions/66058279/token-has-been-expired-or-revoked-google-oauth2-refresh-token-gets-expired-i

![image](https://github.com/swissup/module-email/assets/412612/b41972d7-496f-4163-ad9f-6efe059bdde7)
