### ISSUE TITLE
I can't install this 0.6.2 version, it has an exception prompt

### ISSUE THREAD

**Issue by digitaltotem-net** [swissup/module-email#32]
I tried installing this new 0.6.2 version but I got an exception

**Warning: Undefined array key "swissup_oauth_client_access_token" in /public_html/vendor/magento/framework/Setup/Declaration/Schema/Declaration/SchemaBuilder.php on line 354**

I checked the code and it seems to be because of this line of code inside the **/etc/db_schema.xml** file

**constraint xsi:type="foreign" referenceId="SWISSUP_EMAIL_TOKEN_ID_SWISSUP_OAUTH_CLIENT_ACCESS_TOKEN_ID" table="swissup_email_service" column="token_id" referenceTable="swissup_oauth_client_access_token" referenceColumn="id" onDelete="SET NULL"**

I didn't find this **swissup_oauth_client_access_token** table, the new version doesn't seem to include it?

**Comment by digitaltotem-net** [comment]
> I tried installing this new 0.6.2 version but I got an exception
> 
> **Warning: Undefined array key "swissup_oauth_client_access_token" in /public_html/vendor/magento/framework/Setup/Declaration/Schema/Declaration/SchemaBuilder.php on line 354**
> 
> I checked the code and it seems to be because of this line of code inside the **/etc/db_schema.xml** file
> 
> **constraint xsi:type="foreign" referenceId="SWISSUP_EMAIL_TOKEN_ID_SWISSUP_OAUTH_CLIENT_ACCESS_TOKEN_ID" table="swissup_email_service" column="token_id" referenceTable="swissup_oauth_client_access_token" referenceColumn="id" onDelete="SET NULL"**
> 
> I didn't find this **swissup_oauth_client_access_token** table, the new version doesn't seem to include it?

I found a solution. This version requires installing another plugin "module-oauth2-client"

**Comment by 0m3r** [comment]
https://github.com/swissup/module-email/blob/master/composer.json#L25
