### ISSUE TITLE
Replace Zend_Mail (ZF1) with Zend\Mail\Message (ZF2)

### ISSUE THREAD

**Issue by 0m3r** [swissup/module-email#7]
Zend\Mail\Transport\SMTP almost \Zend_Mail_Transport_Smtp

https://github.com/magento/magento2/pull/8608

In 2.3-develop 
~~~
"zendframework/zend-mail": "^2.9.0",
~~~
https://github.com/magento/magento2/blob/2.3-develop/composer.json#L69

**Comment by roma84** [comment]
Up, 
error in 2.3.0:
Something went wrong while checking the service.The message should be an instance of \Zend_Mail
